language: python
python:
  - "2.7"
  - "3.4"
matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.3"
install:
  - pip install flake8 --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - nosetests
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 lazydb; fi
cache: apt
sudo: false